;;; complementary-light-faces-test.el --- Inventory and gamut tests  -*- lexical-binding: t; -*-

(require 'complementary-light-test-helper)
(require 'complementary-light-generate-faces)

(ert-deftest complementary-light-recorded-inventory-is-fully-classified ()
  (let ((valid '(themed inherit alias preserve external-semantic excluded unavailable))
        missing)
    (dolist (entry (plist-get complementary-light-generated-inventory :faces))
      (let ((rule (complementary-light-face-rule (car entry))))
        (unless (and rule (memq (plist-get (cdr rule) :status) valid))
          (push (car entry) missing))
        (when (eq (plist-get (cdr rule) :status) 'preserve)
          (should (stringp (plist-get (cdr rule) :reason)))))
    (should (null missing)))))

(ert-deftest complementary-light-current-emacs-has-no-new-unclassified-faces ()
  (let* ((stored (mapcar #'car
                         (plist-get complementary-light-generated-inventory :faces)))
         (fresh (mapcar #'car (complementary-light-inventory-discover)))
         (new (cl-set-difference fresh stored)))
    (should (or (null new)
                (ert-fail (format "Unclassified built-in faces: %S" new))))))

(ert-deftest complementary-light-aliases-retain-their-target ()
  (dolist (entry (plist-get complementary-light-generated-inventory :faces))
    (when-let ((target (or (plist-get (cdr entry) :alias-of)
                           (plist-get (cdr entry) :obsolete-alias-of))))
      (let ((rule (complementary-light-face-rule (car entry))))
        (should (eq (plist-get (cdr rule) :status) 'alias))
        (should (eq (plist-get (cdr rule) :target) target))))))

(ert-deftest complementary-light-theme-colors-belong-to-selected-gamut ()
  (let* ((primary 'yellow) (secondary 'purple)
         (allowed (append (mapcar #'cdr complementary-light-neutral-palette)
                          (cl-loop for (_ value) on (complementary-light-palette primary)
                                   by #'cddr collect value)
                          (cl-loop for (_ value) on (complementary-light-palette secondary)
                                   by #'cddr collect value)))
         (terminal-allowed
          (mapcar #'complementary-light--rgb-hex
                  (nthcdr 16 complementary-light--xterm-256-colors))))
    (cl-labels ((check (value permitted)
                  (cond ((and (stringp value)
                              (string-match-p
                               "\\`#[[:xdigit:]]\\{6\\}\\'" value))
                         (should (member value permitted)))
                        ((consp value)
                         (check (car value) permitted)
                         (check (cdr value) permitted)))))
      (dolist (spec (complementary-light-build-face-specs primary secondary))
        (dolist (display (cadr spec))
          (check (cadr display)
                 (if (member '(min-colors 256) (car display))
                     (append allowed terminal-allowed)
                   allowed)))))))

(ert-deftest complementary-light-mode-line-buffer-id-keeps-context-foreground ()
  (let ((rule (cdr (complementary-light-face-rule 'mode-line-buffer-id))))
    (should (eq (plist-get rule :status) 'preserve))
    (should-not (plist-member rule :foreground))))

(ert-deftest complementary-light-active-mode-line-uses-dark-on-light-colors ()
  (let ((rule (cdr (complementary-light-face-rule 'mode-line))))
    (should (eq (plist-get rule :foreground) 'foreground))
    (should (eq (plist-get rule :background) 'surface-raised)))
  (let ((rule (cdr (complementary-light-face-rule 'mode-line-active))))
    (should (eq (plist-get rule :status) 'inherit))
    (should (eq (plist-get rule :target) 'mode-line))))

(ert-deftest complementary-light-rules-declare-colors-only ()
  (dolist (rule complementary-light-face-rules)
    (dolist (attribute complementary-light-non-color-attributes)
      (should-not (plist-member (cdr rule) attribute))))
  (should-not complementary-light-non-color-attribute-allowlist))

(ert-deftest complementary-light-rules-respect-built-in-color-topology ()
  (dolist (rule complementary-light-face-rules)
    (when (eq (plist-get (cdr rule) :status) 'themed)
      (let* ((face (car rule))
             (entry (assq face
                          (plist-get complementary-light-generated-inventory
                                     :faces)))
             (properties (cdr entry)))
        (dolist (attribute complementary-light--color-attributes)
          (when (plist-member (cdr rule) attribute)
            (should
             (complementary-light--default-declares-color-p
              face properties attribute))))))))

(ert-deftest complementary-light-color-topology-exceptions-are-tab-selection-only ()
  (should
   (equal complementary-light-color-topology-allowlist
          '((tab-bar-tab :foreground :background)
            (tab-bar-tab-inactive :foreground)
            (tab-line-tab-current :foreground)))))

(ert-deftest complementary-light-org-block-keeps-built-in-color-topology ()
  (dolist (face '(org-block org-block-begin-line org-block-end-line))
    (let ((rule (cdr (complementary-light-face-rule face))))
      (should (eq (plist-get rule :status) 'inherit))
      (should-not (plist-member rule :foreground))
      (should-not (plist-member rule :background))
      (should-not (assq face
                        (complementary-light-build-face-specs
                         'yellow 'purple))))))

(ert-deftest complementary-light-org-default-colors-use-theme-tokens ()
  (dolist (check '((org-agenda-restriction-lock nil surface-sunken)
                    (org-agenda-structure secondary-text nil)
                    (org-clock-overlay foreground selection-neutral)
                    (org-column nil surface-raised)
                    (org-column-title nil surface-raised)
                    (org-date-selected primary-text nil)
                    (org-dispatcher-highlight primary-on-state primary-state)
                    (org-drawer secondary-text nil)
                    (org-latex-and-related secondary-text nil)
                    (org-mode-line-clock-overrun nil primary-medium)
                    (org-sexp-date secondary-text nil)
                    (org-table secondary-text nil)
                    (org-table-header foreground surface-raised)))
    (let ((rule (cdr (complementary-light-face-rule (car check)))))
      (should (eq (plist-get rule :status) 'themed))
      (should (eq (plist-get rule :foreground) (nth 1 check)))
      (should (eq (plist-get rule :background) (nth 2 check)))))
  ;; `org-hide' deliberately matches the frame background so markup can be
  ;; visually hidden.  Every other Org face that declares a color is themed.
  (dolist (entry (plist-get complementary-light-generated-inventory :faces))
    (let* ((face (car entry))
           (properties (cdr entry))
           (spec (plist-get properties :default-spec)))
      (when (and (equal (plist-get properties :library) "org-faces")
                 (or (complementary-light--tree-contains-symbol-p
                      spec :foreground)
                     (complementary-light--tree-contains-symbol-p
                      spec :background)))
        (if (eq face 'org-hide)
            (should (eq (complementary-light-face-status face) 'preserve))
          (should (eq (complementary-light-face-status face) 'themed)))))))

(ert-deftest complementary-light-local-highlights-use-stronger-surfaces ()
  (let ((rule (cdr (complementary-light-face-rule 'highlight))))
    (should (eq (plist-get rule :background) 'primary-medium)))
  (dolist (check '((match primary-medium)
                    (lazy-highlight secondary-medium)
                    (isearch-fail primary-medium)
                    (pulse-highlight-face primary-medium)
                    (pulse-highlight-start-face primary-medium)
                    (show-paren-match secondary-medium)))
    (let ((rule (cdr (complementary-light-face-rule (car check)))))
      (should (eq (plist-get rule :status) 'themed))
      (should (eq (plist-get rule :background) (cadr check)))))
  (let ((rule (cdr (complementary-light-face-rule 'isearch))))
    (should (eq (plist-get rule :foreground) 'primary-on-state))
    (should (eq (plist-get rule :background) 'primary-state))))

(ert-deftest complementary-light-state-faces-match-their-effective-topology ()
  (let ((success (cdr (complementary-light-face-rule 'success)))
        (exit (cdr (complementary-light-face-rule
                    'compilation-mode-line-exit)))
        (fail (cdr (complementary-light-face-rule
                    'compilation-mode-line-fail)))
        (tab-bar (cdr (complementary-light-face-rule 'tab-bar-tab)))
        (tab-line (cdr (complementary-light-face-rule
                        'tab-line-tab-current))))
    (should (eq (plist-get success :foreground) 'foreground))
    (should (eq (plist-get exit :foreground) 'foreground))
    (should-not (plist-member exit :background))
    (should (eq (plist-get fail :foreground) 'primary-text))
    (should-not (plist-member fail :background))
    (dolist (tab (list tab-bar tab-line))
      (should (eq (plist-get tab :foreground) 'primary-on-state))
      (should (eq (plist-get tab :background) 'primary-state)))))

(ert-deftest complementary-light-active-tab-specs-emit-paired-state-colors ()
  (let* ((primary 'yellow)
         (secondary 'purple)
         (foreground
          (complementary-light-token 'primary-on-state primary secondary))
         (background
          (complementary-light-token 'primary-state primary secondary))
         (specs (complementary-light-build-face-specs primary secondary)))
    (dolist (face '(tab-bar-tab tab-line-tab-current))
      (let ((clauses (cadr (assq face specs))))
        (should
         (cl-some
          (lambda (clause)
            (let ((display (car clause))
                  (attributes (cadr clause)))
              (and (member '(min-colors 257) display)
                   (equal (plist-get attributes :foreground) foreground)
                   (equal (plist-get attributes :background) background))))
          clauses))))))

(ert-deftest complementary-light-comments-use-dedicated-low-emphasis-text ()
  (let ((rule (cdr (complementary-light-face-rule
                    'font-lock-comment-face))))
    (should (eq (plist-get rule :status) 'themed))
    (should (eq (plist-get rule :foreground) 'comment-foreground))))

(ert-deftest complementary-light-common-bundled-modes-use-semantic-colors ()
  (dolist (check '((message-header-name foreground-muted nil)
                    (erc-error-face primary-text nil)
                    (erc-current-nick-face secondary-text nil)
                    (erc-prompt-face primary-on-strong primary-strong)
                    (eww-valid-certificate foreground nil)
                    (elisp-shorthand-font-lock-face primary-text nil)
                    (org-time-grid foreground-muted nil)
                    (org-ellipsis secondary-text nil)
                    (ediff-current-diff-A primary-text primary-subtle)
                    (ediff-fine-diff-B secondary-on-medium secondary-medium)))
    (let ((rule (cdr (complementary-light-face-rule (nth 0 check)))))
      (should (eq (plist-get rule :status) 'themed))
      (should (eq (plist-get rule :foreground) (nth 1 check)))
      (if (nth 2 check)
          (should (eq (plist-get rule :background) (nth 2 check)))
        (should-not (plist-member rule :background))))))

(ert-deftest complementary-light-gnus-uses-semantic-colors ()
  ;; Every Gnus face that owns a color is themed.  `gnus-x-face' is the one
  ;; exception because its black/white pair renders image data rather than UI
  ;; semantics.
  (dolist (entry (complementary-light--inventory-faces))
    (let ((face (car entry))
          (default-spec (plist-get (cdr entry) :default-spec)))
      (when (and (string-prefix-p "gnus-" (symbol-name face))
                 (not (eq face 'gnus-x-face))
                 (or (complementary-light--tree-contains-symbol-p
                      default-spec :foreground)
                     (complementary-light--tree-contains-symbol-p
                      default-spec :background)))
        (should (eq (complementary-light-face-status face) 'themed)))))
  (should (eq (complementary-light-face-status 'gnus-x-face) 'preserve))
  (dolist (check '((gnus-group-mail-1-empty primary-text nil)
                    (gnus-group-news-1-empty secondary-text nil)
                    (gnus-header-subject primary-text nil)
                    (gnus-header-from secondary-text nil)
                    (gnus-cite-3 foreground-muted nil)
                    (gnus-server-denied primary-text nil)
                    (gnus-server-opened foreground nil)
                    (gnus-summary-normal-read foreground-muted nil)
                    (gnus-summary-normal-ticked primary-text nil)
                    (gnus-summary-cancelled primary-on-strong primary-strong)
                    (gnus-emphasis-highlight-words
                     primary-on-state primary-state)))
    (let ((rule (cdr (complementary-light-face-rule (nth 0 check)))))
      (should (eq (plist-get rule :status) 'themed))
      (should (eq (plist-get rule :foreground) (nth 1 check)))
      (if (nth 2 check)
          (should (eq (plist-get rule :background) (nth 2 check)))
        (should-not (plist-member rule :background)))))
  (dolist (check '((gnus-group-mail-1 gnus-group-mail-1-empty)
                    (gnus-summary-high-read gnus-summary-normal-read)
                    (gnus-summary-low-ticked gnus-summary-normal-ticked)))
    (let ((rule (cdr (complementary-light-face-rule (car check)))))
      (should (eq (plist-get rule :status) 'inherit))
      (should (eq (plist-get rule :target) (cadr check))))))

(ert-deftest complementary-light-bundled-background-states-use-safe-surfaces ()
  (dolist (check '((isearch-group-1 primary-on-state primary-state)
                    (isearch-group-2 secondary-on-state secondary-state)
                    (smerge-upper nil primary-subtle)
                    (smerge-lower nil secondary-subtle)
                    (smerge-refined-added nil secondary-medium)
                    (smerge-refined-removed nil primary-medium)
                    (org-habit-overdue-face nil primary-medium)
                    (org-habit-ready-face nil secondary-medium)))
    (let ((rule (cdr (complementary-light-face-rule (car check)))))
      (should (eq (plist-get rule :status) 'themed))
      (if (nth 1 check)
          (should (eq (plist-get rule :foreground) (nth 1 check)))
        (should-not (plist-member rule :foreground)))
      (should (eq (plist-get rule :background) (nth 2 check))))))

(provide 'complementary-light-faces-test)
;;; complementary-light-faces-test.el ends here
